export const getProductsInfoByProductID = (
   productID: string,
   filialId: string
) => {
   return `SELECT DISTINCT SANTRI.PRODUTOS.NOME,
            SANTRI.PRODUTOS.PRODUTO_ID,
            SANTRI.MARCAS.NOME,
            SANTRI.PRODUTOS.UNIDADE,
            SANTRI.PRODUTOS.PRONTA_ENTREGA,
         SANTRI.PRODUTOS.PERMITIR_USO_VENDA_DIRETA,
         SANTRI.PRECOS.PRECO_VENDA,
         SANTRI.PRECOS.DATA_HORA_ALTERACAO
         FROM SANTRI.PRODUTOS, SANTRI.MARCAS, SANTRI.PRECOS
         WHERE SANTRI.PRODUTOS.MARCA_ID = SANTRI.MARCAS.MARCA_ID AND
         SANTRI.PRODUTOS.PRODUTO_ID = SANTRI.PRECOS.PRODUTO_ID AND
         SANTRI.PRECOS.EMPRESA_ID = ${filialId} AND SANTRI.PRODUTOS.PRODUTO_ID = ${productID}`;
};

export const getProductsInfoByBarCode = (barcode: string, filialId: string) => {
   return `SELECT DISTINCT SANTRI.PRODUTOS.NOME,
                 SANTRI.PRODUTOS.PRODUTO_ID,
                 SANTRI.MARCAS.NOME,
                 SANTRI.PRODUTOS.UNIDADE,
                 SANTRI.PRODUTOS.PRONTA_ENTREGA,
                 SANTRI.PRODUTOS.PERMITIR_USO_VENDA_DIRETA,
                 SANTRI.PRECOS.PRECO_VENDA,
                 SANTRI.PRECOS.DATA_HORA_ALTERACAO
   FROM SANTRI.PRODUTOS, SANTRI.MARCAS, SANTRI.PRECOS
  WHERE SANTRI.PRODUTOS.MARCA_ID = SANTRI.MARCAS.MARCA_ID AND
        SANTRI.PRODUTOS.PRODUTO_ID = SANTRI.PRECOS.PRODUTO_ID AND
        SANTRI.PRECOS.EMPRESA_ID = ${filialId} AND
        SANTRI.PRODUTOS.CODIGO_BARRAS = ${barcode}`;
};

export const getPromocionalProductInfoByProductId = (
   productID: string,
   filialId: string
) => {
   return `SELECT PROMO.PRODUTO_ID,
   PROMO.EMPRESA_ID,
   PROMO.PRECO_PROMOCIONAL,
   PROCONDP.DESCRICAO
FROM SANTRI.PROMOCOES_VENDAS               PROMO,
   SANTRI.GRUPOS_PROMOCAO_CONDICAO_PAGTO PROCONDP
WHERE PROMO.GRUPO_PROMOCAO_CONDICAO_ID =
   PROCONDP.GRUPO_PROMOCAO_CONDICAO_ID
AND PROMO.PRODUTO_ID = ${productID}
AND PROMO.EMPRESA_ID = ${filialId}`;
};

export const getStockProductById = (productID: string) => {
   return `SELECT ((SANTRI.ESTOQUES.ESTOQUE_FISICO -
      SANTRI.ESTOQUES.ENTREGAS_PENDENTES) +
      (SANTRI.ESTOQUES.TRANSF_ENTREGAS_PENDENTES -
      SANTRI.ESTOQUES.ESTOQUE_BLOQUEADO)),
      SANTRI.ESTOQUES.COMPRAS_PENDENTES
 FROM SANTRI.ESTOQUES
WHERE SANTRI.ESTOQUES.PRODUTO_ID = ${productID}`;
};

export const getBuyInfoByProductId = (productID: string) => {
   return `SELECT SIC.DATA_HORA_ALTERACAO, SIC.QUANTIDADE
           FROM SANTRI.ITENS_COMPRAS SIC, SANTRI.COMPRAS SC
          WHERE SIC.COMPRA_ID = SC.COMPRA_ID AND SIC.PRODUTO_ID = ${productID} AND
                SC.CONFIRMADA = 'N' AND SC.STATUS = 'B'
          ORDER BY SIC.DATA_HORA_ALTERACAO DESC`;
};
